### ISSUE TITLE
Ensure that mosaic outputs use correct netCDF chunks on disk

### ISSUE THREAD

**Issue by Zac-HD** [ANU-WALD/fire-data-processing#12]
Last I checked they're written as contigious arrays, which is terribly inefficient for timeseries access.  We probably just need to set the encoding on each variable in the final dataset?

(Check most-recent outputs before working on this, it might be fixed)

**Comment by cjtapper** [comment]
@Zac-HD Few questions here, 

1. What are the "correct" netCDF chunks?
2. How do I check these?

**Comment by Zac-HD** [comment]
In this case "correct" just means "the `chunks` setting in the `encoding` attribute of a variable, [which is set here](https://github.com/ANU-WALD/fire-data-processing/blob/master/onetile.py#L181-L183).  The easiest way to check how they're stored on disk is probably

    module load netcdf
    ncdump -h <name of file>

Note that the `-h` argument to `ncdump` means "just the headers, not the file contents" - very important for nontrivial files!

**Comment by cjtapper** [comment]
Great, thanks Zac.
