### ISSUE TITLE
We should use pathlib instead of strings everywhere

### ISSUE THREAD

**Issue by Zac-HD** [ANU-WALD/fire-data-processing#17]
https://docs.python.org/3/library/pathlib.html  I don't *think* we currently have bugs, but this will make it less likely, and Mypy will make it easier to catch missing bits.  `git grep os.path` to make sure we get all of them.

Note: check that Xarray can open things from pathlib paths (including `open_mfdataset`); if not we'll open an issue.

**Comment by kingdion** [comment]
@cjtapper

After about an hour of playing with pathlib I've noticed that pathlib doesn't seem to have support for appending a suffix when a suffix already exists. 

For example, in portions of the code, we add '.no-flammability' or '.new' to files which already have a '.nc' extension. This works when we have strings as paths and we simply concatenate the strings however pathlib paths don't have string concatenation. 

Pathlib has an inbuilt [with_suffix](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.with_suffix) method which either replaces the suffix or appends if it doesn't have one, but no way of dealing with a path which wants an additional suffix to be added. 

What do you suggest I do about this? 
I can go ahead and create new variables with the string concatenations and then convert them to pathlib paths but it will lengthen the code unnecessarily and it raises the question as to whether using pathlib is even worth the trouble. 

In addition, I've tried to append a suffix using [Path.suffixes](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffixes) and [Path.suffix 
](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffix)
(I hope this all makes sense)

**Comment by Zac-HD** [comment]
As long as you get both sides of the read/write, changing the suffix on these temp files isn't a problem - it only does concatenation now because that was easier when working with strings.

**Comment by cjtapper** [comment]
@kingdion seems to work if you do `with_suffix('.nc.new')` or 'with_suffix('.nc.no-flammability')`

**Comment by cjtapper** [comment]
Or `p = p.with_suffix(p.suffix + '.new')`
