### ISSUE TITLE
onetile.py jobs exceeding walltime

### ISSUE THREAD

**Issue by cjtapper** [ANU-WALD/fire-data-processing#22]
https://github.com/ANU-WALD/fire-data-processing/blob/c2204f1aab33ce1e4bf946b931905e991d437876/launchmany.py#L60

Hey @Zac-HD, just wondering if you could explain this line of code for calculating the walltime - a few of the onetile.py jobs exceeded it and failed.

**Comment by Zac-HD** [comment]
`elements / 2400**2` is the fraction of non-NaN pixels, and 40 hours is the estimated year-for-all-land-tile walltime.  You can bump this up if needed; just cap total walltime at 48 hours which is the queue limit.

**Comment by cjtapper** [comment]
Great, makes complete sense now. Thanks!

**Comment by cjtapper** [comment]
https://github.com/ANU-WALD/fire-data-processing/blob/4c5e32c2c0b4a4618600e9340cf0eca2f40fd67a/launchmany.py#L77-L78

@Zac-HD there's also this one. Why is the number of new observations divided by 90?

**Comment by cjtapper** [comment]
I've closed this issue for now. I've adjusted the calculation of walltime required, and it's currently workiing okay. This might need continued monitoring though.
